title: My GitHub Pages Blog
author: Adriano Spinoso
email: adriano.spinoso@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 GitHub Pages tutorial
theme: minima
# social links
twitter_username: adrianospinoso # DO NOT include the @ character, or else the build will fail!
github_username:  adrianospinoso # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
